version: '3'

services:

  database:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_password
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      DATABASE_URL: postgres://default_user:default_password@database:5432/default_db
      PGADMIN_DEFAULT_EMAIL: default_user@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: default_password
    ports:
      - "8002:80"
    networks:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: --start
    environment:
      DATABASE_URL: postgresql://default_user:default_password@database:5432/default_db
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: